Cleanups for Python 3.13
* fix issue with ImportError: cannot import name 'T' from 're' (/home/vijayp/.local/share/uv/python/cpython-3.13.1-linux-x86_64-gnu/lib/python3.13/re/__init__.py) in litellm
* explicitly list scope required
* messy fix to allow this to run on a machine w/o a browser.
* add instruction on binding to public port